spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.d1ialect.PostgreSQL81Dialect
    show-sql: true
server:
  port: 8080


